dist: trusty
language: python
python:
- '2.7'
before_install:
- openssl aes-256-cbc -K $encrypted_ec35d56f228d_key -iv $encrypted_ec35d56f228d_iv -in deploy_key.enc -out deploy_key -d
install:
- pip install simiki
branches:
  only:
  - master
script:
- simiki g
after_success:
- chmod 600 deploy_key
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -avzrtopg --delete -e 'ssh -o StrictHostKeyChecking=no -i deploy_key -p ${DEPLOY_PORT}' output/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}
notifications:
  webhooks:
  - https://api.dongfg.com/webhooks/travisci