language: python
python:
  - '2.7'
install:
  - pip install simiki
branches:
  only:
    - master
script:
  - simiki g
after_success:
  - openssl aes-256-cbc -K $encrypted_ec35d56f228d_key -iv $encrypted_ec35d56f228d_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - cp ssh_config ~/.ssh/config
  - git config user.name "travis-ci"
  - git config user.email "mail@dongfg.com"
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet output ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}
