language: python
python:
  - '2.7'
install:
  - pip install simiki
branches:
  only:
    - master
script:
  - simiki g
after_success:
  - openssl aes-256-cbc -K $encrypted_ec35d56f228d_key -iv $encrypted_ec35d56f228d_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config user.name "travis-ci"
  - git config user.email "mail@dongfg.com"
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avzrtopg -e 'ssh -p ${DEPLOY_PORT}' output/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}
