# Document:
# http://simiki.org/docs/configuration.html

url: https://wiki.dongfg.com/
title: dongfg' wiki
keywords: java, python, linux, docker, wiki, simiki
description: dongfg' personal wiki
author: <a href='https://dongfg.com'>dongfg</a>
theme: yasimple_x2

category:
  - name: linux
    label: Linux/运维
  - name: devops
    label: DevOps
  - name: database
    label: 数据库
  - name: base
    label: 基础
  - name: java
    label: Java
  - name: windows
    label: Windows