# Document:
# http://simiki.org/docs/configuration.html

url: wiki.dongfg.com
title: WiKi
keywords: 
description: 
author: Dongfg

theme: yasimple_x2
deploy:
  - type: rsync
    user: develop
    host: aliyun
    dir: /home/develop/www/dongfg/wiki
