version: "3.1"
services:
  mysql:
    image: mysql
    container_name: dev-server-mysql
    restart: always
    ports:
      - 53306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "4DevOn1y"
  redis:
    image: redis
    container_name: dev-server-redis
    restart: always
    ports:
      - 56379:6379
  mongo:
    image: mongo
    restart: always
    container_name: dev-server-mongo
    ports:
      - 57017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "4DevOn1y"
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: dev-server-rabbitmq
    ports:
      - 55672:5672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: "4DevOn1y"
