name: build and deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image: python:3.6
      env:
        TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          pip install -r requirements.txt
          simiki g
      - name: Upload output artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-folder
          path: output/

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download output artifact
        uses: actions/download-artifact@v3
        with:
          name: output-folder
          path: output/
      - name: deploy cloudflare pages
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy output --project-name=wiki
      - name: deploy github pages
        run: |
          env
          cd output
          echo "wiki.dongfg.com" > CNAME
          git init
          git config --local user.name dongfg
          git config --local user.email mail@dongfg.com
          git remote add origin "https://${{secrets.ACCESS_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git checkout -b gh-pages
          git add --all
          git commit -m "deploy gh-pages"
          git push origin gh-pages -f