name: build and deploy gh-pages
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    name: build and deploy gh-pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.6.15"
          cache: "pip"
      - name: build
        run: |
          pip install -r requirements.txt
          simiki g

      - name: deploy gh-pages
        run: |
          cd build
          echo "wiki.dongfg.com" > CNAME
          git init
          git config --local user.name dongfg
          git config --local user.email mail@dongfg.com
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/$GITHUB_REPOSITORY.git
          git checkout -b gh-pages
          git add --all
          git commit -m "deploy gh-pages"
          git push origin gh-pages -f
