name: build and deploy gh-pages
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    name: build and deploy gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"
      - name: build
        run: |
          curl -sSL https://raw.githubusercontent.com/version-fox/vfox/main/install.sh | bash
          echo "$HOME/.vfox/bin" >> $GITHUB_PATH
          eval "$(vfox activate bash)"
          vfox add python
          vfox install python@3.6.8
          vfox use -g python
          pip install -r requirements.txt
          simiki g

      - name: deploy gh-pages
        run: |
          cd output
          echo "wiki.dongfg.com" > CNAME
          git init
          git config --local user.name dongfg
          git config --local user.email mail@dongfg.com
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/$GITHUB_REPOSITORY.git
          git checkout -b gh-pages
          git add --all
          git commit -m "deploy gh-pages"
          git push origin gh-pages -f
